
import { SideBar } from "@/components/sideBar";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deposito 2 amigos",
  description: "Generated by create next app",
  icons: {
    icon: "/D2AA.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full">
      <body
        className={`flex flex-col min-h-screen antialiased ${geistSans.variable} ${geistMono.variable}`}
      >
        <UserProvider>
          <div className="flex flex-col h-full overflow-hidden">
            <header className="w-full shadow-sm bg-white z-10">
              <Header />
            </header>
            <div className="flex flex-1 h-full">
              <nav className="h-full">
                <SideBar />
              </nav>
              <main className="overflow-auto w-full flex-1 p-4">{children}</main>
            </div>
            <Toaster />
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
